# Generated by Django 6.0.5 on 2026-05-08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_chamado_aberto_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(
                choices=[
                    ('ABERTO', 'Aberto'),
                    ('ANALISE', 'Em análise'),
                    ('ANDAMENTO', 'Em andamento'),
                    ('AGUARDANDO_PECA', 'Aguardando peça'),
                    ('CONCLUIDO', 'Concluído'),
                    ('CANCELADO', 'Cancelado'),
                ],
                default='ABERTO',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='chamado',
            name='andamento',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chamado',
            name='conclusao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chamado',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ChamadoComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('interno', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_chamado', to=settings.AUTH_USER_MODEL)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='chamados.chamado')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ChamadoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=60)),
                ('detalhe', models.TextField(blank=True, default='')),
                ('status_de', models.CharField(blank=True, default='', max_length=20)),
                ('status_para', models.CharField(blank=True, default='', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_chamado', to=settings.AUTH_USER_MODEL)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='chamados.chamado')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
    ]

