# Generated by Django 6.0.5 on 2026-05-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_chamadocomentario_chamadohistorico_chamado_campos_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChamadoComentario',
            new_name='ComentarioChamado',
        ),
        migrations.RenameField(
            model_name='comentariochamado',
            old_name='comentario',
            new_name='texto',
        ),
        migrations.RenameField(
            model_name='comentariochamado',
            old_name='criado_em',
            new_name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='comentariochamado',
            name='interno',
        ),
        migrations.AlterModelOptions(
            name='comentariochamado',
            options={'ordering': ['data_criacao']},
        ),
    ]
