# Generated by Django 6.0.5 on 2026-05-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0005_acqua_manutencao_notificacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='anexo',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='local_intervencao',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='setor',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='tipo_intervencao',
        ),
        migrations.AddField(
            model_name='chamado',
            name='nome_solicitante',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nome do solicitante'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='setor_local',
            field=models.CharField(choices=[('RECEPCAO_1', 'RECEPÇÃO 1'), ('RECEPCAO_2', 'RECEPÇÃO 2'), ('SALA_ATENDIMENTO', 'SALA DE ATENDIMENTO'), ('BANHEIRO_RECEPCAO', 'BANHEIRO DA RECEPÇÃO'), ('DIRECAO_EXECUTIVA', 'SALA DA DIREÇÃO EXECUTIVA'), ('DIRECAO_ADJUNTA_GERENCIA', 'SALA DA DIREÇÃO ADJUNTA/GERÊNCIA'), ('SUPERVISAO_TECNICA', 'SALA DA SUPERVISÃO TÉCNICA'), ('COMUNICACAO', 'SALA DA COMUNICAÇÃO'), ('CONTROLADORIA', 'SALA DA CONTROLADORIA'), ('ORCAMENTO_FARMACIA', 'SALA DO ORÇAMENTO/FARMÁCIA'), ('PRESTACAO_CONTAS', 'SALA DA PRESTAÇÃO DE CONTAS'), ('SALA_REUNIAO', 'SALA DE REUNIÃO'), ('JURIDICO', 'SALA DO JURÍDICO'), ('CONFERENCIA', 'SALA DE CONFERÊNCIA'), ('ENGENHARIA', 'SALA DA ENGENHARIA'), ('FINANCEIRO', 'SALA DO FINANCEIRO'), ('QUALIDADE', 'SALA DA QUALIDADE'), ('RH', 'SALA DO RH'), ('AREA_VIVENCIA', 'ÁREA DE VIVÊNCIA'), ('AREA_CONDENSADORAS', 'ÁREA DAS CONDENSADORAS'), ('DML', 'SALA DO DML'), ('COPA', 'COPA'), ('BANHEIRO_FEMININO', 'BANHEIRO FEMININO'), ('BANHEIRO_MASCULINO', 'BANHEIRO MASCULINO')], default='ENGENHARIA', max_length=80, verbose_name='Setor / Local da solicitação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chamado',
            name='tipo_chamado',
            field=models.CharField(choices=[('INFRAESTRUTURA', 'INFRAESTRUTURA PREDIAL'), ('CLIMATIZACAO', 'CLIMATIZAÇÃO'), ('ELETRICA', 'ELÉTRICA'), ('HIDRAULICA', 'HIDRÁULICA'), ('MOBILIARIO', 'MOBILIÁRIO'), ('EQUIPAMENTO_PATRIMONIO', 'EQUIPAMENTO/PATRIMÔNIO'), ('LIMPEZA_ORGANIZACAO', 'LIMPEZA/ORGANIZAÇÃO'), ('SEGURANCA_PREDIAL', 'SEGURANÇA PREDIAL'), ('OUTROS_ENGENHARIA', 'OUTROS SERVIÇOS DE ENGENHARIA')], default='INFRAESTRUTURA', max_length=80, verbose_name='Tipo de chamado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chamado',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='chamados/', verbose_name='Imagem do problema'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], max_length=20, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('ANALISE', 'Em análise'), ('ANDAMENTO', 'Em andamento'), ('AGUARDANDO', 'Aguardando atendimento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='setor',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='solicitacao_admin_pendente',
            field=models.BooleanField(default=False),
        ),
    ]
